var builder = DistributedApplication.CreateBuilder(args);

// Postgres. Aspire publishes ConnectionStrings__<dbName> to consumers, so
// naming the database resource "default" surfaces as ConnectionStrings:Default
// in the Nomelo.Server configuration (the existing Program.cs reads "Default").
// The admin password is pinned via a parameter so it stays stable across runs;
// otherwise Aspire regenerates a random password each boot and the persistent
// volume's password hash drifts, locking us out.
var postgresPassword = builder.AddParameter("postgres-password", secret: true);
var postgres = builder
    .AddPostgres("postgres", password: postgresPassword)
    .WithDataVolume("nomelo-pgdata")
    .WithPgAdmin();

var db = postgres.AddDatabase("default", databaseName: "nomelo");

// TinyAuth — minimal self-hosted OIDC. Generates its own RSA keys on first boot
// (stored on the volume). We pre-declare the nomelo client via env vars and a
// single admin user for local login. TINYAUTH_AUTH_SECURECOOKIE=false is
// required because TinyAuth itself runs over plain HTTP locally (YARP fronts
// it with HTTPS, see the auth-proxy resource below).
var tinyauthAdminUsers = builder.AddParameter("tinyauth-admin-users", secret: true);
var tinyauthClientSecret = builder.AddParameter("tinyauth-nomelo-client-secret", secret: true);

// TinyAuth v5 hard-requires an HTTPS issuer URL (TINYAUTH_APPURL). Rather than
// terminate TLS inside the TinyAuth container, we expose TinyAuth only on its
// internal targetPort (no host port) and let the auth-proxy YARP resource
// terminate TLS in front of it using the .NET dev cert. The issuer baked into
// tokens is then the YARP-fronted URL, which the server validates against.
//
// We use nomelo.localhost (RFC 6761) rather than bare "localhost" because
// TinyAuth rejects bare "localhost" as APPURL (must be at least a
// second-level domain).
var tinyauth = builder
    .AddContainer("tinyauth", "ghcr.io/steveiliop56/tinyauth", "v5")
    .WithHttpEndpoint(targetPort: 3000, name: "http")
    .WithEnvironment("TINYAUTH_APPURL", "https://nomelo.localhost:8443")
    .WithEnvironment("TINYAUTH_AUTH_USERS", tinyauthAdminUsers)
    .WithEnvironment("TINYAUTH_AUTH_SECURECOOKIE", "false")
    .WithEnvironment("TINYAUTH_OIDC_PRIVATEKEYPATH", "/data/private.key")
    .WithEnvironment("TINYAUTH_OIDC_PUBLICKEYPATH", "/data/public.key")
    .WithEnvironment("TINYAUTH_DATABASE_PATH", "/data/tinyauth.db")
    .WithEnvironment("TINYAUTH_OIDC_CLIENTS_NOMELO_CLIENTID", "nomelo")
    .WithEnvironment("TINYAUTH_OIDC_CLIENTS_NOMELO_CLIENTSECRET", tinyauthClientSecret)
    .WithEnvironment("TINYAUTH_OIDC_CLIENTS_NOMELO_NAME", "nomelo")
    .WithEnvironment(
        "TINYAUTH_OIDC_CLIENTS_NOMELO_TRUSTEDREDIRECTURIS",
        "http://localhost:5000/signin-oidc,http://localhost:5173/signin-oidc")
    .WithVolume("nomelo-tinyauth-data", "/data");

// YARP — TLS terminator for TinyAuth. TinyAuth requires an HTTPS issuer URL;
// running it behind YARP lets us terminate TLS at the proxy with the .NET dev
// cert while TinyAuth itself stays plain HTTP inside the network. The host
// HTTPS port is pinned to 8443 so the OIDC issuer URL is stable across boots.
#pragma warning disable ASPIRECERTIFICATES001 // WithHttpsDeveloperCertificate is experimental in Aspire 13.x
var authProxy = builder.AddYarp("auth-proxy")
    .WithHostHttpsPort(8443)
    .WithHttpsDeveloperCertificate()
    .WithConfiguration(yarp =>
    {
        yarp.AddRoute("/{**catch-all}", tinyauth.GetEndpoint("http"));
    });
#pragma warning restore ASPIRECERTIFICATES001

// Nomelo backend. With a csproj-based AppHost we can use the strongly-typed
// Projects.Nomelo_Server marker (generated by the Aspire SDK from the
// ProjectReference) instead of the string-path overload.
// OIDC__Authority points at the YARP-fronted HTTPS URL, which matches the
// issuer TinyAuth bakes into the tokens (TINYAUTH_APPURL above).
var server = builder
    .AddProject<Projects.Nomelo_Server>("server")
    .WithReference(db)
    .WaitFor(db)
    .WaitFor(tinyauth)
    .WaitFor(authProxy)
    .WithEnvironment("OIDC__Authority", "https://nomelo.localhost:8443")
    .WithEnvironment("OIDC__ClientId", "nomelo")
    .WithEnvironment("OIDC__ClientSecret", tinyauthClientSecret);

// React (Vite) client. AddViteApp runs `npm run dev` in the working dir.
// The Vite dev server listens internally on the port from vite.config.ts (5173);
// Aspire proxies it through a dynamically allocated host port shown in the
// dashboard. Service discovery passes the server URL via services__server__http__0,
// which vite.config.ts can be updated to pick up in a later pass.
var client = builder
    .AddViteApp("client", workingDirectory: "../Nomelo.Client", packageManager: "npm")
    .WithReference(server)
    .WaitFor(server);

builder.Build().Run();
